### PR TITLE
training_drive

### PR DESCRIPTION
**Pull request by nguyenduongZ**
model: 
   unet, runet, rattunet are trained
   nestedunet, attunet have error "empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:"

### CODE REVIEW

**Comment by KhoiDOO** [comment]
Currently, this branch is conflicted with ```main``` branch, please double check and pull request again!

**Comment by KhoiDOO** [comment]
Otherwise, could you capture the issue of nested unet and attunet on tab issue with a detailed description so that I can catch up, then we try to figure that problem. 

Thanks

**Comment by nguyenduongZ** [comment]
I have captured  the issue of nested unet and attunet on tab issue. Please check for me. 
Thanks

**Comment by KhoiDOO** [comment]
Hi Duong owing a conflicting of this pull request, I suggest you check which files are under conflicting then reset that file to the previous commit the pull request again

**Pull request closed without merging**
